name: MLOps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc[gdrive]

      - name: Configure DVC with Google Drive Service Account
        run: |
          echo '${{ secrets.GDRIVE_SEC_CRED_DATA }}' > .dvc/dvc-secondary-project-cf006599baee.json
      
      - name: Verify file location (for debugging)
        run: |
          echo "Contents of .dvc/config:"
          cat .dvc/config
          echo "---------------------------"
          echo "Files in the .dvc directory:"
          ls -la .dvc/

      - name: Pull data from Google Drive (DVC)
        timeout-minutes: 45
        run: dvc pull -v --jobs 4
      # - name: Pull data from Google Drive (DVC)
        # run: dvc pull -v

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: docker compose build

      - name: Start MLflow server in background
        run: docker compose up -d mlflow-server

      - name: Wait for MLflow server to be healthy
        run: |
          echo "Waiting for MLflow server..."
          until curl -s http://localhost:5000 > /dev/null; do
            sleep 1
          done
          echo "MLflow server is up!"

      - name: Run training job
        run: docker compose run --rm train-job

      - name: Stop containers on completion or failure
        if: always()
        run: docker compose down
