name: MLOps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install DVC with Google Drive support
        run: pip install dvc[gdrive]

      - name: Write Google Service Account Credentials
        run: |
          echo "${{ secrets.GDRIVE_SEC_CRED_DATA }}" > gdrive-creds.json
        shell: bash

      - name: Pull data from Google Drive
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gdrive-creds.json
        run: dvc pull -f

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: docker compose build

      - name: Start MLflow server in background
        run: docker compose up -d mlflow-server

      - name: Wait for MLflow server to be healthy
        run: |
          echo "Waiting for MLflow server..."
          while ! curl -s http://localhost:5000; do
            sleep 1
          done
          echo "MLflow server is up!"

      - name: Run training job
        run: docker compose run --rm train-job

      - name: Stop containers on completion or failure
        if: always()
        run: docker compose down
